export const PLATFORM_SIGN_IN = 'PLATFORM_SIGN_IN';

export const PLATFORM_SIGN_OUT = 'PLATFORM_SIGN_OUT';

export const PLATFORM_LOADING = 'PLATFORM_LOADING';

export const PLATFORM_LOADED = 'PLATFORM_LOADED';

export const PLATFORM_ERROR = 'PLATFORM_ERROR';

export const PLATFORM_ERROR_CLEAR = 'PLATFORM_ERROR_CLEAR';
